#!/bin/bash --login

source $HOME/bin/env.sh

# Clear Rails cache
#(cd $IDEALS_HOME ; RAILS_ENV=$RAILS_ENV bundle exec rake ideals:rails_cache:clear )

$HOME/bin/start-passenger

echo "Started IDEALS"
