#!/bin/bash --login

source $HOME/bin/env.sh

(cd $IDEALS_HOME ; RAILS_ENV=$RAILS_ENV bundle install ; RAILS_ENV=$RAILS_ENV bundle exec passenger start -d -e $RAILS_ENV --nginx-config-template nginx.conf.erb --max-pool-size 20 )
