#!/bin/bash --login

source $HOME/bin/env.sh

# Stop Passenger
( cd $IDEALS_HOME ; RAILS_ENV=$RAILS_ENV bundle exec passenger stop )

# Stop Delayed Job
( cd $IDEALS_HOME ; RAILS_ENV=$RAILS_ENV bin/delayed_job -n 10 stop )

echo "Stopped IDEALS"

exit 0
