#!/usr/bin/env bash
#ideals-bin-scripts/svc_hooks/shutdown
###
### shutdown - service hook for booting up ideals; called by
###        /etc/init.d/ideals
###

# Load environment variables
. $HOME/.bashrc

source $HOME/bin/env.sh

# Stop Rails
$HOME/bin/stop-rails